name: Release 3X-UI for alpine

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build x-ui (amd64)
      run: |
        mkdir x-ui
        docker run -itd -e XRAY_VMESS_AEAD_FORCED=false --platform linux/amd64 --network=host --restart=unless-stopped --name 3x-ui-amd64 ghcr.io/mhsanaei/3x-ui:latest
        sleep 10
        docker cp 3x-ui-amd64:/app/ ./x-ui/
        docker rm -f 3x-ui-amd64

    - name: Package (amd64)
      run: tar -zcvf x-ui-linux-alpine-amd64.tar.gz x-ui

    - name: Upload Artifacts (amd64)
      uses: actions/upload-artifact@v4
      with:
        name: x-ui-linux-alpine-amd64
        path: x-ui-linux-alpine-amd64.tar.gz

    - name: Upload Release Asset (amd64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: x-ui-linux-alpine-amd64.tar.gz
        asset_name: x-ui-linux-alpine-amd64.tar.gz
        prerelease: true

  build-arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up QEMU (for ARM64 emulation)
      uses: docker/setup-qemu-action@v3

    - name: Build x-ui (arm64)
      run: |
        mkdir x-ui
        docker run -itd -e XRAY_VMESS_AEAD_FORCED=false --platform linux/arm64 --network=host --restart=unless-stopped --name 3x-ui-arm64 ghcr.io/mhsanaei/3x-ui:latest
        sleep 10
        docker cp 3x-ui-arm64:/app/ ./x-ui/
        docker rm -f 3x-ui-arm64

    - name: Package (arm64)
      run: tar -zcvf x-ui-linux-alpine-arm64.tar.gz x-ui

    - name: Upload Artifacts (arm64)
      uses: actions/upload-artifact@v4
      with:
        name: x-ui-linux-alpine-arm64
        path: x-ui-linux-alpine-arm64.tar.gz

    - name: Upload Release Asset (arm64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: x-ui-linux-alpine-arm64.tar.gz
        asset_name: x-ui-linux-alpine-arm64.tar.gz
        prerelease: true
